name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bundle: msi,nsis
          - os: macos-latest
            target: x86_64-apple-darwin
            bundle: dmg,app
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bundle: deb,appimage

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'GlChemDraw ${{ github.ref_name }}'
          releaseBody: |
            GlChemDraw ${{ github.ref_name }} - Cross-platform Chemistry Structure Drawing & NMR Analysis

            What's New
            - Fixed React Hooks Error: Resolved 'Invalid hook call' errors
            - Fixed Structure Drawing Loading: Implemented dynamic loading
            - Enhanced Error Handling: Added comprehensive error boundaries
            - Cross-platform Support: Windows, Mac, and Linux builds

            Downloads
            - Windows: MSI and NSIS installers
            - Mac: DMG and APP bundles
            - Linux: DEB and AppImage packages

            System Requirements
            - Windows: Windows 10/11 (64-bit)
            - Mac: macOS 10.15+ (64-bit)
            - Linux: Ubuntu 18.04+ or equivalent
            - Memory: 4GB RAM minimum, 8GB recommended
            - Storage: 500MB free space
            - Display: 1280x800 minimum resolution
          releaseDraft: false
          prerelease: false
          includeDebug: false
          includeSource: false
